name: Terraform Apply (main)

on:
  push:
    branches:
      - main

jobs:
  apply:
    name: Terraform Apply
    runs-on: ubuntu-latest

    permissions:
      contents: read
      id-token: write  # Para o AWS Actions funcionar corretamente

    defaults:
      run:
        working-directory: terraform

    steps:
      - name: Checkout código
        uses: actions/checkout@v3

      - name: Configurar credenciais AWS
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Instalar Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.6.6

      - name: Terraform Init
        run: terraform init

      - name: Terraform Validate
        run: terraform validate

      - name: Terraform Apply
        run: terraform apply -auto-approve

      - name: Detectar Mudanças no Frontend
        id: detect_index
        run: |
          if [ "${{ github.event.before }}" = "0000000000000000000000000000000000000000" ]; then
            echo "Primeiro commit detectado — forçando upload."
            echo "CHANGED=true" >> $GITHUB_OUTPUT
          else
            CHANGED=$(git diff --name-only ${{ github.event.before }} ${{ github.sha }} | grep -q 'frontend/public/index.html' && echo true || echo false)
            echo "CHANGED=$CHANGED" >> $GITHUB_OUTPUT
          fi

      - name: Fazendo upload do Frontend no S3
        if: steps.detect_index.outputs.CHANGED == 'true'
        run: |
          aws s3 cp frontend/public/index.html s3://$S3_BUCKET_NAME/index.html --acl public-read
        env:
          S3_BUCKET_NAME: frontend-bucket-mackenzie-prat-prof
